### ISSUE TITLE
Scraping solution for Indivisible

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/cta-aggregator#100]
Goal: Have Indivisible actions in our data store.

Solving this issue may involve identifying omissions in the OSDI spec that prevent us from fully ingesting Indivisible data, and a multi-step solution to getting the data in, starting perhaps with manual entry and working up to automated ingestion.

**Comment by bnd5k** [comment]
I found this URL listing events.

http://act.indivisible.org/event/local-actions/search/

Is this everything that we'd need to scrape or are there more URLs?
