### ISSUE TITLE
Scraping solution for Wall of Us

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/cta-aggregator#101]
Goal: Have Wall-of-us actions in our data store. (https://www.wallofus.org/actions)

Solving this issue may involve identifying omissions in the OSDI spec that prevent us from fully ingesting Wall-of-us data, and a multi-step solution to getting the data in, starting perhaps with manual entry and working up to automated ingestion.

**Comment by bnd5k** [comment]
What would a scraper look like?  Would it just need to grab the 4 listed on their homepage or are there other parts of the site that contiain CTAs?

https://www.wallofus.org/

**Comment by bnd5k** [comment]
Scraping this is doable, but there's an extra step where users are required to log in in order to see the contact info for the targets and scripts/templates.  

We would need to create and account for the scraper, so it could enter credentials and log in to get that info.

**Comment by AaronSofaer** [comment]
WallOfUs is at least partially the project of someone who's part of Ragtag. Let's talk about this on Slack.
