### ISSUE TITLE
CTAs should be soft-deletable

### ISSUE THREAD

**Issue by AaronSofaer** [RagtagOpen/cta-aggregator#35]
A deletion for a CTA should just set a field or status to be "deleted" or "inactive" or something, and it shouldn't come up in queries unless someone specifically adds a query parameter to get deleted events (in which case they should come up). This will be useful for muting bad data but will make the system useless for suppressing good data, just so the system design remains aligned with desired outcomes.

**Comment by bnd5k** [comment]
How are you envisioning a CTA transitions from active to inactive?  Would it be done by manually updating the DB, some via an app or script?
Would you want to record who made the change to the record?
