### ISSUE TITLE
Filtering on advocacy campaigns based on OCD-ID

### ISSUE THREAD

**Issue by AaronSofaer** [RagtagOpen/cta-aggregator#59]
Consumers will want to be able to get actions based on OCD-ID, e.g. I am in this locality and what are ACs that are relevant to me?

**Comment by bnd5k** [comment]
To anyone available to address this this issue: check out the Target resource.  

https://github.com/RagtagOpen/cta-aggregator/blob/develop/app/resources/v1/target_resource.rb#L3

It looks like the API can already do this, so maybe we can close this ticket updating the documentation.
