### ISSUE TITLE
Consume all of Resistance Calendar

### ISSUE THREAD

**Issue by AaronSofaer** [RagtagOpen/cta-aggregator#66]
Now that pagination works... though they said we can just consume all of it every hour or two, they don't mind.

**Comment by john** [comment]
Ingest from here: https://resistance-calendar.herokuapp.com/v1/events

**Comment by bnd5k** [comment]
Done.

PRs: 
* https://github.com/RagtagOpen/cta-scraper/pull/19
* https://github.com/RagtagOpen/cta-scraper/pull/20
