### ISSUE TITLE
Consume Eventbrite events on a tag-filtered basis

### ISSUE THREAD

**Issue by AaronSofaer** [RagtagOpen/cta-aggregator#67]
Since RC isn't doing so, it would be valuable to pick a dozen tags, consume all of the Eventbrite events with those tags. This is requested by act.today's malus from ProgCode.

**Comment by bnd5k** [comment]
@AaronSofaer Can you provide more information? 
Which tags do you want to use? 
Can you post a URL of an example of the sort of CTA you're hoping the scraper can find?

**Comment by AaronSofaer** [comment]
Example:  https://www.eventbrite.com/e/indivisible-sf-general-meeting-sunday-october-1-2017-tickets-38212481561?aff=es2

Tag filtered basis might not be the right thing. Potentially a POST to the API with an Eventbrite URL and then the API consumes that page would make more sense.

**Comment by bnd5k** [comment]
It's still unclear how a scraper navigate from  https://www.eventbrite.com to https://www.eventbrite.com/e/indivisible-sf-general-meeting-sunday-october-1-2017-tickets-38212481561?aff=es2.

How are you envisioning this navigation/discovery will happen?

**Comment by AaronSofaer** [comment]
I'm thinking that maybe the correct thing is to have a function in the API that allows people who care about Eventbrite events (like Rally) to send those to the API very easily. A POST to an endpoint with an eventbrite URL could trigger the scraper to create the resource.

I'm going to follow up with the requestor and see what they envisioned, because this came from external and it was a while ago.
