### ISSUE TITLE
Consume events from People's Calendar

### ISSUE THREAD

**Issue by AaronSofaer** [RagtagOpen/cta-aggregator#68]
This is requested by act.today's malus from ProgCode.

**Comment by bnd5k** [comment]
@AaronSofaer Can you fill this issue about a bit more? Is this an API or a website? Can you post a link to where they're storing CTAs currently?

**Comment by AaronSofaer** [comment]
I'm closing this issue. Resistance Calendar is already scraping People's Calendar, so there's no need to build a separate scraper.
