### ISSUE TITLE
Default to only upcoming in API

### ISSUE THREAD

**Issue by AaronSofaer** [RagtagOpen/cta-aggregator#71]
From sync-up call:

"How should the API handle past events?  Currently all events are visible and API consumers can add a filter to their request to retrieve only upcoming events.  Maybe the API should default showing upcoming events and requiring a special filter for retrieving past events.  Does this seem like a worthwhile feature or should we just tell consumers to use the `upcoming` filter?"

**Comment by UnderpantsGnome** [comment]
@AaronSofaer @bnd5k my thinking here is the default filter is `upcoming` and adding a new filter for `past`. Let me know if that works for you.

**Comment by AaronSofaer** [comment]
Closed as done by Michael Moen in August. :)
