### ISSUE TITLE
Hide user_id for non-admins

### ISSUE THREAD

**Issue by AaronSofaer** [RagtagOpen/cta-aggregator#72]
From sync-up call

"Each resource contains a `user_id` attribute.  It's meaningless to API consumers, since they have no knowledge of who the other users might be.  Should we make the user_id visible only to admins?"

**Comment by UnderpantsGnome** [comment]
I don't see a `user_id` in the output, but I do see the `user` relation. We can probably just remove the `has_one :user` from the resources if you don't want to expose it.

**Comment by UnderpantsGnome** [comment]
Ah I see there is a `user_id` in the target attributes in the target_list on AdvocacyCampaign.
