### ISSUE TITLE
Work with OSDI to implement Tags for events/ACs

### ISSUE THREAD

**Issue by AaronSofaer** [RagtagOpen/cta-aggregator#80]
... and potentially all other first-order resources?

**Comment by ben-pr-p** [comment]
Osdi has tags for events / anything. The tagging resource has the `item_type` field, and then the variable resource name field that points to the item.

I like this a lot, since it mirrors my sql tagging join table, where I have `people_taggings`, `event_taggings`, each with different foreign keys

**Comment by AaronSofaer** [comment]
Per discussion with Ben in ProgCode Slack: there is a pending PR-to-be-created which will rework the Tags documentation to have it refer to all noun-y first order resources rather than just to Person resources. This will entirely fulfill our needs. I'll close this Issue when that PR gets created, with a link to the PR.
