### ISSUE TITLE
Work with OSDI to implement Organizations as potential hosts for Events

### ISSUE THREAD

**Issue by AaronSofaer** [RagtagOpen/cta-aggregator#82]
Organization rather than Person

**Comment by ben-pr-p** [comment]
See if this is enough for your needs https://github.com/opensupporter/osdi-docs/pull/293

**Comment by AaronSofaer** [comment]
That doesn't address why we want Organizations as a resource in their own right, no.

**Comment by ben-pr-p** [comment]
Oh, I would like Organizations or Group as an independent resource, yeah. Happy to collaborate on drafting that
