### ISSUE TITLE
Work with OSDI to add a target number of signatures to a Petition resource

### ISSUE THREAD

**Issue by AaronSofaer** [RagtagOpen/cta-aggregator#83]
This should just be us opening a PR

**Comment by ben-pr-p** [comment]
There's a target property, with a target hash, but I'm not quite sure what it's intended for – http://opensupporter.github.io/osdi-docs/petitions.html#targets

**Comment by AaronSofaer** [comment]
It's the target of _whom you are petitioning_; e.g., if you are petitioning the California AG to file charges against companies violating environmental regulations, the target property contains the Target resource for the California AG.
