### ISSUE TITLE
Work with OSDI to flesh out Fundraising Pages

### ISSUE THREAD

**Issue by AaronSofaer** [RagtagOpen/cta-aggregator#84]
Needs relationships with ACs and Events, possibly more

**Comment by ben-pr-p** [comment]
We should discuss this on the eventual OSDI PR, but I would actually like Advocacy Campaigns linked to Events, and Advocacy Campaigns linked to Fundraising Pages, and not Fundraising Pages to events

**Comment by AaronSofaer** [comment]
If there's a fundraising event, literally something along the lines of this:

https://secure.actblue.com/donate/83andme-sf

it doesn't seem like an AC at all; it's clearly an Event linked to a Fundraising Page or some other sort of Fundraise resource.
