### ISSUE TITLE
Decide on & implement dedupe-update logic

### ISSUE THREAD

**Issue by AaronSofaer** [RagtagOpen/cta-aggregator#86]
We need to be automatically handling deduplication of entries that are either scraped from multiple hosting sites or scraped from our manual input spreadsheet on multiple rows.

We should figure out what the canonical "this is the same event" set of attributes are, and probably have some sort of system for saying "ok, this is the same event, but with new data, so don't create a new event, update an existing one".

**Comment by bnd5k** [comment]
@AaronSofaer this is way too vague.  Can you fill out this ticket with more detail?

**Comment by AaronSofaer** [comment]
@bnd5k filled out some detail.
