### ISSUE TITLE
Add share_url to AdvocacyCampaign

### ISSUE THREAD

**Issue by alexwilkinson** [RagtagOpen/cta-aggregator#94]
As a prerequisite for #88, we want to make sure that we can persist a share URL included with a campaign. Adding this attribute will also bring our `AdvocacyCampaign` model more in compliance with OSDI http://opensupporter.github.io/osdi-docs/advocacy_campaigns.html#advocacy-campaign-fields.

**Comment by bnd5k** [comment]
PR: https://github.com/RagtagOpen/cta-aggregator/pull/96
